import { NextResponse } from "next/server";
import { projectDataPrisma as db } from "@/lib/projectDataPrisma";
import { dateValue, requireProjectDataAccess, safeJson } from "@/lib/projectDataAccess";

const resources = ["KPI", "SALES_SUMMARY", "DISCOUNT_SOURCE", "DISCOUNT_MAPPING", "DISCOUNT_RECORD", "PRODUCT", "SYNC_CONFIG"] as const;
type Resource = typeof resources[number];
const validResource = (value: string): value is Resource => (resources as readonly string[]).includes(value);
const text = (value: unknown, label: string, max = 200) => { const result = String(value ?? "").trim(); if (!result || result.length > max) throw new Error(`${label}不能为空或超过 ${max} 字。`); return result; };
const optional = (value: unknown, max = 200) => { const result = String(value ?? "").trim(); return result ? result.slice(0, max) : null; };
const number = (value: unknown, label: string, fallback?: number) => { if ((value === "" || value == null) && fallback !== undefined) return fallback; const result = Number(value); if (!Number.isFinite(result)) throw new Error(`${label}必须是有效数字。`); return result; };

export async function GET(request: Request) {
  try {
    const url = new URL(request.url); const projectId = text(url.searchParams.get("projectId"), "项目ID", 80); const resource = String(url.searchParams.get("resource") ?? "");
    if (!validResource(resource)) return NextResponse.json({ error: "资源类型无效。" }, { status: 400 });
    await requireProjectDataAccess(projectId, "READ");
    const take = Math.min(500, Math.max(1, Number(url.searchParams.get("limit")) || 100));
    const data = resource === "KPI" ? await db.projectKpi.findMany({ where: { projectId }, orderBy: { periodStart: "desc" }, take })
      : resource === "SALES_SUMMARY" ? await db.projectSalesSummary.findMany({ where: { projectId }, orderBy: { periodStart: "desc" }, take })
      : resource === "DISCOUNT_SOURCE" ? await db.projectDiscountSource.findMany({ where: { projectId }, orderBy: { createdAt: "desc" }, take })
      : resource === "DISCOUNT_MAPPING" ? await db.projectDiscountFieldMapping.findMany({ where: { sourceId: { in: (await db.projectDiscountSource.findMany({ where: { projectId }, select: { id: true } })).map((item) => item.id) } }, orderBy: { updatedAt: "desc" }, take })
      : resource === "DISCOUNT_RECORD" ? await db.projectDiscountRecord.findMany({ where: { projectId }, orderBy: { occurredAt: "desc" }, take })
      : resource === "PRODUCT" ? await db.projectProduct.findMany({ where: { projectId }, orderBy: { updatedAt: "desc" }, take })
      : await db.projectSyncConfig.findMany({ where: { projectId }, orderBy: { updatedAt: "desc" }, take });
    return NextResponse.json({ data });
  } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "读取项目数据失败。" }, { status: 403 }); }
}

export async function POST(request: Request) {
  try {
    const body = await request.json(); const projectId = text(body.projectId, "项目ID", 80); const resource = String(body.resource ?? "");
    if (!validResource(resource)) return NextResponse.json({ error: "资源类型无效。" }, { status: 400 });
    const { session } = await requireProjectDataAccess(projectId, "EDIT");
    let data: unknown;
    if (resource === "KPI") {
      const periodStart = dateValue(body.periodStart, "开始日期"), periodEnd = dateValue(body.periodEnd, "结束日期"); if (periodEnd < periodStart) throw new Error("结束日期不能早于开始日期。");
      const metricKey = text(body.metricKey, "指标键"); data = await db.projectKpi.upsert({ where: { projectId_metricKey_periodStart_periodEnd: { projectId, metricKey, periodStart, periodEnd } }, update: { metricName: text(body.metricName, "指标名"), targetValue: body.targetValue == null ? null : number(body.targetValue, "目标值"), actualValue: body.actualValue == null ? null : number(body.actualValue, "实际值"), unit: optional(body.unit), currency: optional(body.currency, 10) }, create: { projectId, metricKey, metricName: text(body.metricName, "指标名"), periodStart, periodEnd, targetValue: body.targetValue == null ? null : number(body.targetValue, "目标值"), actualValue: body.actualValue == null ? null : number(body.actualValue, "实际值"), unit: optional(body.unit), currency: optional(body.currency, 10), createdById: session.userId } });
    } else if (resource === "SALES_SUMMARY") {
      const periodStart = dateValue(body.periodStart, "开始日期"), periodEnd = dateValue(body.periodEnd, "结束日期"), marketplace = optional(body.marketplace, 30) ?? "", currency = text(body.currency, "币种", 10).toUpperCase();
      data = await db.projectSalesSummary.upsert({ where: { projectId_periodStart_periodEnd_marketplace_currency: { projectId, periodStart, periodEnd, marketplace, currency } }, update: { orderCount: number(body.orderCount, "订单数", 0), units: number(body.units, "销量", 0), grossSales: number(body.grossSales, "销售额", 0), netSales: number(body.netSales, "净销售额", 0), refundAmount: number(body.refundAmount, "退款", 0), discountAmount: number(body.discountAmount, "折扣", 0), rawSummary: safeJson(body.rawSummary) }, create: { projectId, sourceFileId: optional(body.sourceFileId, 80), periodStart, periodEnd, marketplace, currency, orderCount: number(body.orderCount, "订单数", 0), units: number(body.units, "销量", 0), grossSales: number(body.grossSales, "销售额", 0), netSales: number(body.netSales, "净销售额", 0), refundAmount: number(body.refundAmount, "退款", 0), discountAmount: number(body.discountAmount, "折扣", 0), rawSummary: safeJson(body.rawSummary) } });
    } else if (resource === "DISCOUNT_SOURCE") data = await db.projectDiscountSource.create({ data: { projectId, name: text(body.name, "数据源名称"), sourceType: text(body.sourceType, "数据源类型", 50), platform: optional(body.platform, 50), sourceUrl: optional(body.sourceUrl, 2000), appToken: optional(body.appToken, 200), tableId: optional(body.tableId, 200), viewId: optional(body.viewId, 200), headerRowIndex: Math.min(5, Math.max(1, number(body.headerRowIndex, "表头行号", 1))), configuration: safeJson(body.configuration), lastOperatedById: session.userId, lastOperatedAt: new Date(), createdById: session.userId } });
    else if (resource === "DISCOUNT_MAPPING") { const sourceId = text(body.sourceId, "数据源ID", 80); const source = await db.projectDiscountSource.findFirst({ where: { id: sourceId, projectId } }); if (!source) throw new Error("折扣数据源不存在。"); const targetField = text(body.targetField, "目标字段"); data = await db.projectDiscountFieldMapping.upsert({ where: { sourceId_targetField: { sourceId, targetField } }, update: { sourceField: text(body.sourceField, "源字段", 500) }, create: { sourceId, targetField, sourceField: text(body.sourceField, "源字段", 500) } }); }
    else if (resource === "DISCOUNT_RECORD") { const sourceId = text(body.sourceId, "数据源ID", 80); const source = await db.projectDiscountSource.findFirst({ where: { id: sourceId, projectId } }); if (!source) throw new Error("折扣数据源不存在。"); const originalPrice = body.originalPrice == null || body.originalPrice === "" ? null : number(body.originalPrice, "划线价"); const discountPrice = body.discountPrice == null || body.discountPrice === "" ? null : number(body.discountPrice, "折扣价"); const calculatedRate = originalPrice && discountPrice != null ? Math.round(((originalPrice-discountPrice)/originalPrice)*10000)/100 : null; data = await db.projectDiscountRecord.create({ data: { projectId, sourceId, occurredAt: body.startDate ? dateValue(body.startDate, "开始时间") : new Date(), currency: text(body.currency || "USD", "币种", 10).toUpperCase(), grossAmount: originalPrice ?? 0, discountAmount: originalPrice != null && discountPrice != null ? originalPrice-discountPrice : 0, netAmount: discountPrice ?? 0, rawData: safeJson(body.rawData), salesType: optional(body.salesType), productCategory: optional(body.productCategory), asin: optional(body.asin), productLink: optional(body.productLink, 2000), originalPrice, discountPrice, discountRate: body.discountRate == null || body.discountRate === "" ? calculatedRate : number(body.discountRate, "折扣率"), startDate: body.startDate ? dateValue(body.startDate, "开始时间") : null, endDate: body.endDate ? dateValue(body.endDate, "结束时间") : null, promoCode: optional(body.promoCode), accCampaignId: optional(body.accCampaignId), accGoldRatio: body.accGoldRatio == null || body.accGoldRatio === "" ? null : number(body.accGoldRatio, "ACC佣金比例"), lastUpdated: new Date(), dealType: optional(body.dealType), brand: optional(body.brand) || source.name, platform: optional(body.platform), store: optional(body.store) } }); }
    else if (resource === "PRODUCT") { const asin = text(body.asin, "ASIN"), marketplace = optional(body.platform, 30) ?? optional(body.marketplace, 30) ?? "", sku = optional(body.sku) ?? asin; const payload = { asin, name: optional(body.category) ?? asin, brand: optional(body.brand), sequence: optional(body.sequence), store: optional(body.store), category: optional(body.category), platform: marketplace || null, bsrRank: optional(body.bsrRank), rating: body.rating == null || body.rating === "" ? null : number(body.rating, "评分"), linkPosition: optional(body.linkPosition), productLink: optional(body.productLink, 2000), reviewCount: body.reviewCount == null || body.reviewCount === "" ? null : Math.round(number(body.reviewCount, "评论数")) }; data = await db.projectProduct.upsert({ where: { projectId_sku_marketplace: { projectId, sku, marketplace } }, update: payload, create: { projectId, sku, marketplace, ...payload } }); }
    else { const syncType = text(body.syncType, "同步类型", 50), provider = text(body.provider, "服务商", 50); data = await db.projectSyncConfig.upsert({ where: { projectId_syncType_provider: { projectId, syncType, provider } }, update: { enabled: !!body.enabled, schedule: optional(body.schedule), configuration: safeJson(body.configuration), secretReference: optional(body.secretReference, 300) }, create: { projectId, syncType, provider, enabled: !!body.enabled, schedule: optional(body.schedule), configuration: safeJson(body.configuration), secretReference: optional(body.secretReference, 300), createdById: session.userId } }); }
    return NextResponse.json({ data }, { status: 201 });
  } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "保存项目数据失败。" }, { status: 400 }); }
}
