import Link from "next/link";
import { PARTY_B_COMPANIES } from "@/lib/partyB";
import { decodeConfirmation } from "@/lib/contractConfirmationStore";
import { FrameworkSignedUpload } from "./FrameworkSignedUpload";
import { AddendumForm, ContractNumberEditor } from "./ContractRecordTools";
import { FrameworkWorkflow, type FrameworkTimelineRow } from "./FrameworkWorkflow";

type Props = { contract: any; isAdmin: boolean; canEdit: boolean; canReview: boolean; internal: boolean; selectedId?: string; timeline: FrameworkTimelineRow[] };
const stateLabel: Record<string, string> = { DRAFT: "字段填写中 / 待选择审核", REVIEWING: "审核中", REJECTED: "审核退回", SIGNING: "合同签署中", COMPLETED: "合同签署完成", EFFECTIVE: "已生效", VOID: "已作废" };
const value = (input: unknown) => input === null || input === undefined || input === "" ? "—" : String(input);
const money = (row: { amount: number; currency: string } | null | undefined) => row ? `${row.currency} ${row.amount}` : "未选择";

export function FrameworkContractDetail({ contract, isAdmin, canEdit, canReview, internal, selectedId, timeline }: Props) {
  const confirmations = contract.projectConfirmations.flatMap((row: any) => { try { return [{ ...decodeConfirmation(row), raw: row }]; } catch { return []; } });
  const selected = confirmations.find((row: any) => row.id === selectedId) ?? confirmations[0];
  const partyB = PARTY_B_COMPANIES[contract.partyBCompany as keyof typeof PARTY_B_COMPANIES];
  const accounts = contract.receivingAccounts.flatMap((row: any) => { try { return [JSON.parse(row.snapshot)]; } catch { return []; } });
  const d = selected?.draft;
  const exportUrl = selected
    ? `/api/contracts/${contract.id}/framework-export?selection=both&confirmationId=${encodeURIComponent(selected.id)}`
    : `/api/contracts/${contract.id}/framework-export?selection=master`;
  return <main className="mx-auto max-w-[1500px] space-y-6">
    <header className="flex flex-col gap-4 border-b border-slate-200 pb-5 lg:flex-row lg:items-start lg:justify-between">
      <div><Link href="/contracts" className="text-sm text-slate-500 hover:text-slate-800">← 返回合同列表</Link><div className="mt-3 flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold text-slate-950">{contract.contractNo}</h1><Status value={stateLabel[contract.status] || contract.status} tone={contract.status === "COMPLETED" ? "green" : "amber"} /></div><p className="mt-2 text-sm text-slate-600">主格式合同管理双方主体资料；每份项目确认书独立记录合作范围、收费条款和签署原件。</p></div>
      {internal && <div className="flex flex-wrap gap-2">{isAdmin && <ContractNumberEditor contractId={contract.id} contractNo={contract.contractNo} />}{canEdit && <Link className="btn-secondary" href={`/contracts/new?contractId=${contract.id}`}>{contract.status === "COMPLETED" ? "管理员修改合同" : "编辑主合同资料"}</Link>}{["SIGNING", "COMPLETED"].includes(contract.status) && <a className="btn-secondary" href={`/api/contracts/${contract.id}/framework-export?selection=master`}>导出主格式合同</a>}{selected && ["SIGNING", "COMPLETED"].includes(contract.status) && <a className="btn-secondary" href={`/api/contracts/${contract.id}/framework-export?selection=both&confirmationId=${selected.id}`}>导出主合同＋当前确认书</a>}<Link className="btn-primary" href={`/contracts/${contract.id}/confirmations`}>管理项目确认书</Link></div>}
    </header>
    <nav aria-label="合同内容导航" className="flex gap-2 overflow-x-auto border-b border-slate-200 pb-3"><a href="#master" className="btn-secondary whitespace-nowrap">主格式合同</a><a href="#confirmations" className="btn-secondary whitespace-nowrap">项目确认书（{confirmations.length}）</a><a href="#signed" className="btn-secondary whitespace-nowrap">签署与原件</a></nav>
    {internal && <FrameworkWorkflow contractId={contract.id} status={contract.status} reviewerName={contract.reviewer?.name || ""} canEdit={canEdit} canReview={canReview} selectedExportUrl={exportUrl} timeline={timeline} />}
    <section id="master" className="space-y-4 scroll-mt-24"><SectionTitle title="主格式合同" description="主体、联系人及约定收款账户；不重复展示确认书中的项目计费字段。" />
      <div className="grid gap-4 xl:grid-cols-2"><InfoSection title="甲方信息" rows={[["公司名称/发票抬头", contract.partyA],["信用代码/商业登记号", contract.partyACreditCode],["地址", contract.partyAAddress],["指定联系人", contract.partyAContact],["电子邮箱", contract.partyAEmail],["电话", contract.partyAPhone]]} /><InfoSection title="乙方信息" rows={[["签约主体", partyB?.name],["信用代码/商业登记号", contract.partyBCreditCode || partyB?.creditCode],["地址", contract.partyBAddress || partyB?.address],["指定联系人", contract.partyBContact],["电子邮箱", contract.partyBEmail],["电话", contract.partyBPhone]]} /></div>
      <div className="grid gap-4 lg:grid-cols-[1fr_2fr]"><InfoSection title="管理信息" rows={[["关联客户", contract.customer?.brandName],["创建方式", contract.uploadType === "EXISTING" ? "上传已有品牌方合同" : "网站创建品牌方合同"],["合同负责人", contract.owner?.name],["审核人", contract.reviewer?.name],["创建人", contract.createdBy?.name],["合同模板", contract.template?.name],["备注", contract.remark]]} /><section className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-semibold text-slate-900">乙方收款账户</h3><div className="mt-4 grid gap-3 sm:grid-cols-2">{accounts.map((a: any, index: number) => <div key={`${a.profileId || a.accountNumber}-${index}`} className="rounded-lg bg-slate-50 p-4 text-sm"><p className="font-medium text-slate-900">{value(a.accountName || a.name)}</p><p className="mt-2 text-slate-600">{value(a.bankName)} · {value(a.accountNumber)}</p><p className="mt-1 text-slate-600">SWIFT/税号：{value(a.swiftCode)}</p><p className="mt-1 text-slate-600">银行地址：{value(a.bankAddress)}</p></div>)}{!accounts.length && <p className="text-sm text-slate-500">未选择收款账户</p>}</div></section></div>
    </section>
    <section id="confirmations" className="space-y-4 scroll-mt-24"><SectionTitle title="项目确认书" description="同一主合同可有多份确认书；选择一份查看其完整字段，互不覆盖。" />
      <div className="flex gap-2 overflow-x-auto pb-1">{confirmations.map((row: any) => <Link key={row.id} href={`/contracts/${contract.id}?confirmation=${row.id}#confirmations`} className={`whitespace-nowrap rounded-lg border px-3 py-2 text-sm ${row.id === selected?.id ? "border-purple-600 bg-purple-50 font-medium text-purple-800" : "border-slate-200 text-slate-700"}`}>{row.number} · {stateLabel[row.status] || row.status}</Link>)}</div>
      {!selected ? <div className="rounded-xl border border-dashed border-slate-300 p-8 text-center"><p className="text-sm text-slate-600">尚无项目确认书</p>{canEdit && <Link href={`/contracts/${contract.id}/confirmations`} className="mt-3 inline-flex text-sm text-purple-700">新建项目确认书 →</Link>}</div> : <div className="space-y-4">
        <div className="grid gap-4 xl:grid-cols-2"><InfoSection title="项目与合作周期" rows={[["确认书编号", selected.number],["状态", stateLabel[selected.status] || selected.status],["品牌/店铺", d.brand],["店铺链接", d.storeUrl],["合作开始", d.startDate],["合作结束", d.endDate],["最低合作周期", d.minimumMonths === null ? "—" : `${d.minimumMonths}个月`],["服务说明", d.serviceDescription]]} /><InfoSection title="确认书联系人" rows={[["甲方联系人", d.partyAContact?.name],["甲方邮箱", d.partyAContact?.email],["甲方电话", d.partyAContact?.phone],["乙方联系人", d.partyBContact?.name],["乙方邮箱", d.partyBContact?.email],["乙方电话", d.partyBContact?.phone]]} /></div>
        <section className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-semibold text-slate-900">国家、平台与服务范围</h3><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr><th className="px-3 py-2">国家（站点）</th><th className="px-3 py-2">销售平台</th><th className="px-3 py-2">使用 Program</th><th className="px-3 py-2">第三方平台</th></tr></thead><tbody>{d.scopes.map((scope: any, i: number) => <tr key={i} className="border-t border-slate-100"><td className="px-3 py-3 font-medium">{scope.country}</td><td className="px-3 py-3">{scope.salesPlatforms.join("、")}</td><td className="px-3 py-3">{scope.programs.join("、")}</td><td className="px-3 py-3">{scope.thirdPartyPlatforms.join("、")}</td></tr>)}</tbody></table></div></section>
        <div className="grid gap-4 xl:grid-cols-3"><InfoSection title="推广产品范围" rows={[["范围", d.productScope === "ALL" ? "全店商品" : "指定推广商品"],["产品", d.productScope === "ALL" ? "全店商品" : d.products.map((p: any) => `${p.name}（${p.country}）`).join("；")]]} /><InfoSection title="收费模式" rows={[["月度服务费", money(d.monthlyFee)],["销售佣金", d.commission ? d.commission.mode === "PACKAGE" ? `总包佣金 ${value(d.commission.packageValue)}` : `GMV服务佣金 ${value(d.commission.serviceRatePercent)}%` : "未选择"],["佣金口径", d.commission?.basis],["归因窗口", `${d.attributionWindowDays}日`],["订单锁定期", `${d.orderLockDays}日`],["尾期", `${d.tailDays}日`]]} /><InfoSection title="销售数据与付款" rows={[["销售数据来源", d.salesSources.join("、")],["结算/付款说明", d.paymentTerms],["尾期说明", d.tailTerms],["附加费用", d.additionalFees.length ? d.additionalFees.map((f: any) => `${f.description} ${f.currency} ${f.amount}`).join("；") : "无"]]} /></div>
      </div>}
    </section>
    <section id="signed" className="space-y-4 scroll-mt-24"><SectionTitle title="签署与原件" description="导出仅生成待签文件，不改变状态；一次上传盖章完整版，可同时归档主合同和文件内的项目确认书。" /><div className="rounded-xl border border-slate-200 bg-white p-5"><FrameworkSignedUpload contractId={contract.id} expectedUpdatedAt={contract.updatedAt.toISOString()} canSign={canEdit} signed={contract.status === "COMPLETED" && Boolean(contract.fileUrl)} confirmations={confirmations.map((row: any) => ({ id: row.id, number: row.number, status: row.status }))} /></div></section>
    {internal && <section className="space-y-4"><SectionTitle title="附加条款与补充文件" description="主合同签署后如需补充约定，保留原合同并追加条款和文件。" /><div className="rounded-xl border border-slate-200 bg-white p-5"><AddendumForm contractId={contract.id} /><div className="mt-4 space-y-2">{contract.addenda.map((row: any) => <div key={row.id} className="flex flex-wrap justify-between gap-2 rounded-lg bg-slate-50 p-3 text-sm"><span><b>{row.title}</b>{row.terms ? ` · ${row.terms}` : ""}</span>{row.fileUrl && <a className="text-purple-700" href={row.fileUrl}>下载补充文件</a>}</div>)}{!contract.addenda.length && <p className="text-sm text-slate-500">暂无附加条款</p>}</div></div></section>}
  </main>;
}

function SectionTitle({ title, description }: { title: string; description: string }) { return <div><h2 className="text-lg font-semibold text-slate-950">{title}</h2><p className="mt-1 text-sm text-slate-600">{description}</p></div>; }
function InfoSection({ title, rows }: { title: string; rows: Array<[string, unknown]> }) { return <section className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-semibold text-slate-900">{title}</h3><dl className="mt-4 grid gap-x-6 gap-y-4 sm:grid-cols-2">{rows.map(([label, content]) => <div key={label} className="min-w-0"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 break-words text-sm text-slate-900">{value(content)}</dd></div>)}</dl></section>; }
function Status({ value: label, tone }: { value: string; tone: "green" | "amber" }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-medium ${tone === "green" ? "bg-emerald-50 text-emerald-800" : "bg-amber-50 text-amber-800"}`}>{label}</span>; }
