"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ChevronLeft, Pencil, Plus, Trash2, X } from "lucide-react";

type Project = { id: string; name: string; ownerId: string | null; ownerName: string };
type Owner = { id: string; name: string };
type Target = { id: string; month: string; monthlyTarget: number; currency: string; project: { id: string; name: string }; amOwner: Owner | null };
type Draft = { key: string; projectId: string; newProjectName: string; ownerId: string; currency: string; monthlyTarget: string };

const currentMonth = new Date().toISOString().slice(0, 7);
const blank = (projects: Project[]): Draft => ({ key: crypto.randomUUID(), projectId: projects[0]?.id ?? "", newProjectName: "", ownerId: projects[0]?.ownerId ?? "", currency: "USD", monthlyTarget: "" });
const money = (value: number, currency: string) => new Intl.NumberFormat("zh-CN", { style: "currency", currency: currency === "RMB" ? "CNY" : currency, maximumFractionDigits: 0 }).format(value);

export default function KpiConfigClient({ projects, owners }: { projects: Project[]; owners: Owner[] }) {
  const [month, setMonth] = useState(currentMonth);
  const [rows, setRows] = useState<Target[]>([]);
  const [drafts, setDrafts] = useState<Draft[]>([]);
  const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const load = useCallback(async () => { setBusy(true); setError(""); try { const res = await fetch(`/api/project-data/kpi-batch?month=${month}&scope=all`); const json = await res.json(); if (!res.ok) throw new Error(json.error); setRows(json.data || []); } catch (e) { setError(e instanceof Error ? e.message : "加载失败"); } finally { setBusy(false); } }, [month]);
  useEffect(() => { void load(); }, [load]);
  const showAdd = (target?: Target) => { setDrafts(target ? [{ key: crypto.randomUUID(), projectId: target.project.id, newProjectName: "", ownerId: target.amOwner?.id ?? "", currency: target.currency, monthlyTarget: String(target.monthlyTarget) }] : [blank(projects)]); setOpen(true); };
  const update = (key: string, values: Partial<Draft>) => setDrafts((all) => all.map((row) => row.key === key ? { ...row, ...values } : row));
  const save = async () => { setBusy(true); setError(""); try { const res = await fetch("/api/project-data/kpi-batch", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ month, rows: drafts.map(({ key: _key, ...row }) => ({ ...row, monthlyTarget: Number(row.monthlyTarget) })) }) }); const json = await res.json(); if (!res.ok) throw new Error(json.error); setOpen(false); await load(); } catch (e) { setError(e instanceof Error ? e.message : "保存失败"); } finally { setBusy(false); } };
  const remove = async (id: string) => { if (!confirm("确认删除这条月度目标？")) return; const res = await fetch("/api/project-data/kpi-batch", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); const json = await res.json(); if (!res.ok) setError(json.error || "删除失败"); else await load(); };
  return <div className="space-y-6">
    <div><Link href="/projects" className="inline-flex items-center gap-1 text-sm text-slate-500 hover:text-slate-900"><ChevronLeft className="h-4 w-4"/>返回项目管理</Link><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-bold text-slate-900">项目 KPI 配置</h1><p className="mt-1 text-sm text-slate-500">按月维护项目 GMV 目标与 AM 负责人</p></div><button className="btn-primary" onClick={() => showAdd()}><Plus className="h-4 w-4"/>批量新增 KPI</button></div></div>
    <section className="card overflow-hidden"><div className="grid items-center gap-3 border-b border-slate-100 px-4 py-4 sm:grid-cols-[auto_12rem_1fr] sm:px-5"><span className="text-sm font-medium text-slate-600">考核月份</span><input type="month" className="input w-full" value={month} onChange={(e) => setMonth(e.target.value)}/><span className="w-fit rounded-full bg-slate-100 px-3 py-1 text-sm text-slate-600">共 {rows.length} 条</span></div>
      {error && <div className="m-4 rounded-lg bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}
      <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">项目</th><th>AM 负责人</th><th>考核月份</th><th>月度 GMV 目标</th><th>80% 达标线</th><th className="pr-5 text-right">操作</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => <tr key={row.id} className="hover:bg-slate-50/70"><td className="px-5 py-4 font-medium text-slate-900">{row.project.name}</td><td>{row.amOwner?.name || "未指定"}</td><td>{row.month}</td><td className="font-semibold">{money(row.monthlyTarget, row.currency)}</td><td className="text-emerald-700">{money(row.monthlyTarget * .8, row.currency)}</td><td className="pr-5 text-right"><button className="p-2 text-slate-500 hover:text-brand-700" onClick={() => showAdd(row)} aria-label="编辑"><Pencil className="h-4 w-4"/></button><button className="p-2 text-slate-500 hover:text-rose-600" onClick={() => void remove(row.id)} aria-label="删除"><Trash2 className="h-4 w-4"/></button></td></tr>)}</tbody></table>{!busy && !rows.length && <div className="py-16 text-center text-sm text-slate-500">该月份暂无 KPI 配置</div>}</div>
    </section>
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div className="w-full max-w-6xl rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b px-6 py-4"><div><h2 className="text-lg font-semibold">批量新增 KPI</h2><p className="text-sm text-slate-500">考核月份：{month}</p></div><button onClick={() => setOpen(false)}><X className="h-5 w-5"/></button></div><div className="max-h-[65vh] space-y-3 overflow-y-auto p-6">{drafts.map((row, index) => <div key={row.key} className="grid gap-3 rounded-xl border border-slate-200 p-4 md:grid-cols-[1.5fr_1fr_.6fr_1fr_auto]"><label className="text-xs text-slate-500">项目<select className="input mt-1 w-full" value={row.projectId} onChange={(e) => { const p = projects.find((item) => item.id === e.target.value); update(row.key, { projectId: e.target.value, ownerId: p?.ownerId || row.ownerId }); }}><option value="">＋ 手动新增项目</option>{projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select>{!row.projectId && <input className="input mt-2 w-full" placeholder="新项目名称" value={row.newProjectName} onChange={(e) => update(row.key, { newProjectName: e.target.value })}/>}</label><label className="text-xs text-slate-500">AM 负责人<select className="input mt-1 w-full" value={row.ownerId} onChange={(e) => update(row.key, { ownerId: e.target.value })}><option value="">请选择</option>{owners.map((o) => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label className="text-xs text-slate-500">币种<select className="input mt-1 w-full" value={row.currency} onChange={(e) => update(row.key, { currency: e.target.value })}>{["USD","GBP","EUR","RMB"].map((c) => <option key={c}>{c}</option>)}</select></label><label className="text-xs text-slate-500">月度 GMV 目标<input className="input mt-1 w-full" type="number" min="0" step="0.01" value={row.monthlyTarget} onChange={(e) => update(row.key, { monthlyTarget: e.target.value })}/><span className="mt-1 block text-[11px] text-slate-400">80%：{Number(row.monthlyTarget || 0) * .8}</span></label><button className="self-center p-2 text-slate-400 hover:text-rose-600" disabled={drafts.length === 1} onClick={() => setDrafts((all) => all.filter((item) => item.key !== row.key))}><Trash2 className="h-4 w-4"/><span className="sr-only">删除第{index + 1}行</span></button></div>)}</div><div className="flex items-center justify-between border-t px-6 py-4"><button className="btn-secondary" onClick={() => setDrafts((all) => [...all, blank(projects)])}><Plus className="h-4 w-4"/>增加一行</button><div className="flex gap-2"><button className="btn-secondary" onClick={() => setOpen(false)}>取消</button><button className="btn-primary" disabled={busy} onClick={() => void save()}>{busy ? "保存中…" : `保存 ${drafts.length} 条`}</button></div></div></div></div>}
  </div>;
}
