"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { ArrowRightLeft, Database, FileSpreadsheet, Loader2, Plus, RefreshCw, Trash2, Upload, X } from "lucide-react";
import { cn } from "@/lib/utils";

type Project = { id: string; name: string };
type Platform = { code: string; name: string };
type RawFile = { id: string; projectId: string; sourceType: string; dataMonth: string; projectCurrency: string | null; originalAmount: number; detectedCurrency: string | null; originalName: string; sizeBytes: number; status: string; uploadedAt: string; importSummary: string };
type Processed = { id: string; projectId: string; dataMonth: string; currency: string; totalAmount: number; platformBreakdown: Record<string, number>; exchangeRates: Record<string, number>; files: RawFile[] };

const currentMonth = () => new Date().toLocaleDateString("sv-SE", { timeZone: "Asia/Shanghai", year: "numeric", month: "2-digit" });
const money = (value: number, currency: string) => `${({ USD: "$", EUR: "€", GBP: "£", CNY: "¥", JPY: "¥" } as Record<string,string>)[currency] ?? `${currency} `}${value.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const statusMeta: Record<string, [string,string]> = { UPLOADED:["待处理","bg-slate-100 text-slate-700"], PROCESSING:["处理中","bg-brand-50 text-brand-700"], COMPLETED:["已完成","bg-emerald-50 text-emerald-700"], FAILED:["失败","bg-rose-50 text-rose-700"], CURRENCY_PENDING:["货币待确认","bg-amber-50 text-amber-700"] };

export default function SourceDataClient({ projects }: { projects: Project[] }) {
  const [tab,setTab]=useState<"raw"|"processed">("raw");
  const [uploadMonth,setUploadMonth]=useState(currentMonth()); const [uploadProject,setUploadProject]=useState(""); const [uploadPlatform,setUploadPlatform]=useState("");
  const [filterMonth,setFilterMonth]=useState(currentMonth()); const [filterProject,setFilterProject]=useState(""); const [filterPlatform,setFilterPlatform]=useState("");
  const [platforms,setPlatforms]=useState<Platform[]>([]); const [eligibleIds,setEligibleIds]=useState<Set<string>>(new Set());
  const [rawRows,setRawRows]=useState<RawFile[]>([]); const [processed,setProcessed]=useState<Processed[]>([]); const [selected,setSelected]=useState<Set<string>>(new Set());
  const [loading,setLoading]=useState(false); const [uploading,setUploading]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [showPlatformForm,setShowPlatformForm]=useState(false);
  const inputRef=useRef<HTMLInputElement>(null);
  const projectName=(id:string)=>projects.find(item=>item.id===id)?.name??"—"; const platformName=(code:string)=>platforms.find(item=>item.code===code)?.name??code;

  const load=useCallback(async()=>{setLoading(true);setError("");try{const q=new URLSearchParams({view:tab,month:filterMonth});if(filterProject)q.set("projectId",filterProject);if(filterPlatform)q.set("platform",filterPlatform);const r=await fetch(`/api/project-data/sources?${q}`);const b=await r.json();if(!r.ok)throw new Error(b.error||"加载失败");if(tab==="raw")setRawRows(b.data||[]);else setProcessed(b.data||[]);}catch(e){setError(e instanceof Error?e.message:"加载失败");}finally{setLoading(false);}},[filterMonth,filterPlatform,filterProject,tab]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{void(async()=>{try{const [s,k]=await Promise.all([fetch("/api/project-data/data-sources").then(r=>r.json()),fetch(`/api/project-data/kpi-batch?month=${uploadMonth}&scope=all`).then(r=>r.json())]);setPlatforms(s.data||[]);setEligibleIds(new Set((k.data||[]).map((item:{projectId:string})=>item.projectId)));}catch{setEligibleIds(new Set());}})();},[uploadMonth]);
  const eligible=projects.filter(item=>eligibleIds.has(item.id));

  const upload=async(files:FileList|null)=>{if(!files?.length||!uploadProject||!uploadPlatform)return;setUploading(true);setError("");let done=0;const warnings:string[]=[];for(const file of Array.from(files)){const form=new FormData();form.set("projectId",uploadProject);form.set("sourceType",uploadPlatform);form.set("dataMonth",uploadMonth);form.set("file",file);try{const r=await fetch("/api/project-data/sources",{method:"POST",body:form});const b=await r.json();if(!r.ok)throw new Error(b.error);done++;if(b.warning)warnings.push(`${file.name}：${b.warning}`);if(b.currencyConflict)warnings.push(`${file.name}：检测到货币与项目币种不一致，请在文件列表确认`);}catch(e){warnings.push(e instanceof Error?e.message:`${file.name} 上传失败`);}}setNotice(`已上传 ${done}/${files.length} 个文件${warnings.length?`；${warnings.join("；")}`:"，数据已自动处理"}`);setFilterMonth(uploadMonth);setFilterProject(uploadProject);setUploading(false);if(inputRef.current)inputRef.current.value="";await load();};
  const act=async(file:RawFile,action:"process"|"confirmCurrency",currency?:string)=>{setLoading(true);try{const r=await fetch("/api/project-data/sources",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,id:file.id,projectId:file.projectId,currency})});const b=await r.json();if(!r.ok)throw new Error(b.error);if(b.currencyConflict)setNotice(`检测到 ${b.detectedCurrency}，项目币种为 ${b.projectCurrency}，请确认后再入汇总。`);else setNotice(`${file.originalName} 已处理并重新计算汇总。`);await load();}catch(e){setError(e instanceof Error?e.message:"处理失败");}finally{setLoading(false);}};
  const remove=async(ids:string[])=>{if(!ids.length||!confirm(`确认删除选中的 ${ids.length} 个文件？删除后会重新计算项目月度汇总。`))return;const r=await fetch("/api/project-data/sources",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids})});const b=await r.json();if(!r.ok){setError(b.error||"删除失败");return;}setSelected(new Set());setNotice(`已删除 ${b.deletedCount} 个文件并重新计算汇总。`);await load();};
  const recalc=async(projectId:string,dataMonth:string)=>{const r=await fetch("/api/project-data/sources",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"recalculate",projectId,dataMonth})});if(!r.ok){const b=await r.json();setError(b.error||"重新计算失败");}else{setNotice(`${projectName(projectId)} ${dataMonth} 汇总已重新计算。`);await load();}};
  const allSelected=rawRows.length>0&&rawRows.every(file=>selected.has(file.id));
  const totals=useMemo(()=>processed.reduce<Record<string,number>>((out,item)=>{out[item.currency]=(out[item.currency]||0)+item.totalAmount;return out;},{}),[processed]);

  return <div className="mx-auto max-w-[1500px] space-y-6 pb-10">
    <header className="border-b border-slate-200 pb-5"><Link href="/projects" className="text-sm font-medium text-brand-700 hover:underline">← 返回项目进度跟踪</Link><p className="mt-5 text-xs font-bold tracking-[.24em] text-slate-500">DATA MANAGEMENT</p><h1 className="mt-2 text-4xl font-black tracking-tight text-slate-950">数据管理</h1></header>
    <div className="inline-flex rounded-xl bg-slate-100 p-1">{([['raw','原始数据'],['processed','已处理数据']] as const).map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={cn("min-w-40 rounded-lg px-5 py-2.5 text-sm font-medium",tab===key?"bg-white text-slate-950 shadow-sm":"text-slate-600")}>{label}</button>)}</div>
    {tab==="raw"&&<section className="card p-4 sm:p-6"><h2 className="text-lg font-semibold">上传数据文件</h2><div className="mt-5 grid items-end gap-3 sm:grid-cols-2 xl:grid-cols-[.8fr_1.2fr_1.2fr_auto]">
      <label className="text-xs font-semibold text-slate-600">数据月份<input type="month" className="input mt-1 block w-44" value={uploadMonth} onChange={e=>setUploadMonth(e.target.value)}/></label>
      <label className="text-xs font-semibold text-slate-600">关联客户<select className="input mt-1 block min-w-60" value={uploadProject} onChange={e=>setUploadProject(e.target.value)}><option value="">{eligible.length?"请选择":"当月无 KPI 配置项目"}</option>{eligible.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
      <label className="text-xs font-semibold text-slate-600">数据来源平台<span className="mt-1 flex gap-1"><select className="input min-w-52" value={uploadPlatform} onChange={e=>setUploadPlatform(e.target.value)}><option value="">请选择平台</option>{platforms.map(item=><option key={item.code} value={item.code}>{item.name}</option>)}</select><button className="btn-secondary h-10 w-10 p-0" onClick={()=>setShowPlatformForm(true)} aria-label="新增平台"><Plus className="h-4 w-4"/></button></span></label>
      <input ref={inputRef} type="file" multiple accept=".xlsx,.xls,.csv" className="hidden" onChange={e=>void upload(e.target.files)}/><button className="btn-primary h-10" disabled={uploading||!uploadProject||!uploadPlatform} onClick={()=>inputRef.current?.click()}>{uploading?<Loader2 className="h-4 w-4 animate-spin"/>:<Upload className="h-4 w-4"/>}{uploading?"上传处理中…":"选择文件（可多选）"}</button>
    </div><p className="mt-3 text-xs text-slate-500">支持 .xlsx / .xls / .csv。上传后按平台金额列与 date 列月份自动处理；失败时可在列表手动重处理。</p></section>}
    {showPlatformForm&&<form className="card p-5" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch("/api/project-data/data-sources",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:f.get("name"),code:f.get("code"),sourceUrl:f.get("sourceUrl")})});const b=await r.json();if(!r.ok){setError(b.error);return;}setPlatforms(old=>[...old,b.data]);setUploadPlatform(b.data.code);setShowPlatformForm(false);}}><div className="flex justify-between"><b>新增数据来源平台</b><button type="button" onClick={()=>setShowPlatformForm(false)}><X className="h-4 w-4"/></button></div><div className="mt-3 grid gap-3 sm:grid-cols-3"><input name="name" required className="input" placeholder="平台名称"/><input name="code" required className="input" placeholder="平台代码"/><input name="sourceUrl" className="input" placeholder="来源链接（可选）"/></div><div className="mt-3 text-right"><button className="btn-primary">保存平台</button></div></form>}
    {notice&&<div className="rounded-lg bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{notice}</div>}{error&&<div className="rounded-lg bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</div>}
    {tab==="raw"?<section className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div className="flex items-center gap-2"><Database className="h-4 w-4 text-brand-600"/><b>文件列表　共 {rawRows.length} 个</b></div><Filters month={filterMonth} setMonth={setFilterMonth} project={filterProject} setProject={setFilterProject} platform={filterPlatform} setPlatform={setFilterPlatform} projects={projects} platforms={platforms} loading={loading} load={load}/></div>
      {selected.size>0&&<div className="flex justify-between border-b bg-brand-50 px-4 py-2 text-sm"><span>已选择 {selected.size} 项</span><button className="inline-flex items-center gap-1 text-rose-700" onClick={()=>void remove([...selected])}><Trash2 className="h-4 w-4"/>批量删除</button></div>}
      <div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-600"><tr><th className="px-4 py-3"><input type="checkbox" checked={allSelected} onChange={()=>setSelected(allSelected?new Set():new Set(rawRows.map(f=>f.id)))}/></th>{["文件名","项目","平台","月份","大小","状态","上传时间","操作"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{rawRows.map(file=>{const meta=statusMeta[file.status]||[file.status,"bg-slate-100"];return <tr key={file.id}><td className="px-4 py-3"><input type="checkbox" checked={selected.has(file.id)} onChange={()=>setSelected(old=>{const n=new Set(old);n.has(file.id)?n.delete(file.id):n.add(file.id);return n;})}/></td><td><span className="inline-flex items-center gap-2 font-medium"><FileSpreadsheet className="h-4 w-4 text-emerald-600"/>{file.originalName}</span></td><td>{projectName(file.projectId)}</td><td>{platformName(file.sourceType)}</td><td>{file.dataMonth}</td><td>{(file.sizeBytes/1024).toFixed(1)} KB</td><td><span className={cn("rounded-full px-2 py-1 text-xs",meta[1])}>{meta[0]}</span></td><td className="text-xs text-slate-500">{new Date(file.uploadedAt).toLocaleString("zh-CN")}</td><td><div className="flex items-center gap-2"><button className="text-brand-700" onClick={()=>void act(file,"process")}>数据处理</button>{file.status==="CURRENCY_PENDING"&&<button className="text-amber-700" onClick={()=>{const currency=prompt(`检测到 ${file.detectedCurrency}，项目币种 ${file.projectCurrency}。请输入确认使用的币种：`,file.detectedCurrency||file.projectCurrency||"USD");if(currency)void act(file,"confirmCurrency",currency.toUpperCase());}}>确认货币</button>}<button className="text-rose-600" onClick={()=>void remove([file.id])}>删除</button></div></td></tr>})}</tbody></table>{!loading&&!rawRows.length&&<Empty text="暂无文件"/>}</div></section>
    :<section className="space-y-4"><div className="card flex flex-wrap items-center justify-between gap-3 p-4"><div className="flex flex-wrap gap-3">{Object.entries(totals).map(([currency,total])=><span key={currency} className="rounded-lg bg-slate-50 px-4 py-2 text-sm"><b>{money(total,currency)}</b> 已处理汇总</span>)}</div><Filters month={filterMonth} setMonth={setFilterMonth} project={filterProject} setProject={setFilterProject} platform={filterPlatform} setPlatform={setFilterPlatform} projects={projects} platforms={platforms} loading={loading} load={load}/></div>{processed.map(item=>{const currencyTotals=item.files.reduce<Record<string,number>>((out,file)=>{const c=file.detectedCurrency||item.currency;out[c]=(out[c]||0)+file.originalAmount;return out;},{});return <article key={item.id} className="card overflow-hidden"><header className="flex flex-wrap items-center justify-between gap-3 border-b bg-slate-50/70 px-5 py-3"><div className="flex items-center gap-2"><b>{projectName(item.projectId)}</b><span className="rounded-full border px-2 py-0.5 text-xs">{item.currency}</span></div><div className="flex items-center gap-3">{Object.entries(item.exchangeRates).map(([key,rate])=><span key={key} className="inline-flex items-center gap-1 text-xs text-slate-500"><ArrowRightLeft className="h-3 w-3"/>{key.replace("_TO_"," → ")}：{rate}</span>)}<button className="inline-flex items-center gap-1 text-xs text-brand-700" onClick={()=>void recalc(item.projectId,item.dataMonth)}><RefreshCw className="h-3.5 w-3.5"/>重新计算汇总</button></div></header><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="px-5 py-3">文件名</th><th>平台</th><th>货币</th><th className="pr-5 text-right">原始金额</th></tr></thead><tbody className="divide-y">{item.files.map(file=><tr key={file.id}><td className="px-5 py-3">{file.originalName}</td><td>{platformName(file.sourceType)}</td><td>{file.detectedCurrency||item.currency}</td><td className="pr-5 text-right font-mono">{money(file.originalAmount,file.detectedCurrency||item.currency)}</td></tr>)}{Object.keys(currencyTotals).length>1&&<tr className="bg-slate-50"><td className="px-5 py-3 text-xs font-semibold" colSpan={3}>原币小计</td><td className="pr-5 text-right">{Object.entries(currencyTotals).map(([c,v])=><span key={c} className="ml-3 font-mono text-xs">{money(v,c)}</span>)}</td></tr>}<tr className="bg-brand-50/70"><td className="px-5 py-3 font-semibold" colSpan={3}>项目汇总（{item.currency}）</td><td className="pr-5 text-right font-bold">{money(item.totalAmount,item.currency)}</td></tr></tbody></table></article>})}{!loading&&!processed.length&&<div className="card"><Empty text="暂无已处理数据"/></div>}</section>}
  </div>;
}

function Filters({month,setMonth,project,setProject,platform,setPlatform,projects,platforms,loading,load}:{month:string;setMonth:(v:string)=>void;project:string;setProject:(v:string)=>void;platform:string;setPlatform:(v:string)=>void;projects:Project[];platforms:Platform[];loading:boolean;load:()=>Promise<void>}){return <div className="grid w-full gap-2 sm:grid-cols-2 lg:w-auto lg:grid-cols-[10rem_10rem_10rem_auto]"><input type="month" className="input w-full" value={month} onChange={e=>setMonth(e.target.value)}/><select className="input w-full" value={project} onChange={e=>setProject(e.target.value)}><option value="">全部客户</option>{projects.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="input w-full" value={platform} onChange={e=>setPlatform(e.target.value)}><option value="">全部平台</option>{platforms.map(item=><option key={item.code} value={item.code}>{item.name}</option>)}</select><button className="btn-secondary w-full" onClick={()=>void load()}><RefreshCw className={cn("h-4 w-4",loading&&"animate-spin")}/>刷新</button></div>}
function Empty({text}:{text:string}){return <div className="py-14 text-center"><FileSpreadsheet className="mx-auto h-8 w-8 text-slate-300"/><p className="mt-3 text-sm text-slate-500">{text}</p></div>}
